### ISSUE TITLE
Alternatives to GitBook for publishing documentation

### ISSUE THREAD

**Issue by flodolo** [mozilla/firefox-data-docs#162] opened 2018-07-17 08:37 UTC
As I was talking with @Dexterp37, I noticed that you are using GitBook to generate https://docs.telemetry.mozilla.org/

I wonder if you already evaluated alternatives, given that the CLI is not developed anymore, and GitBook is focusing on hosted documentation.
https://github.com/GitbookIO/gitbook/issues/1808

**Comment by badboy** [comment] 2018-07-17 16:12
Interesting. At least for now mdbook is still working, even if not developed anymore.
However we might want to look into alternatives eventually, especially if we want some bugs fixed. [mdbook](https://github.com/rust-lang-nursery/mdBook) might be a near-drop-in replacement, it's maintained and actively used by the Rust project.
I ran a quick test and it looks like it might provide most features; we'd need to add support for mermaid graphs and add ga support.

**Comment by harterrt** [comment] 2018-07-17 16:58
Just checking in for the record. It looks like you all are on the right track. 

We started with Gitbook because it met our needs at the time and would be easy to abandon if it turned out to be a dud. The CLI being abandoned seems like a sufficient reason to leave Gitbook.

So far we have had a few consistent complaints with Gitbook:
* Slow compile time, esp as documentation grows
* Forward and back buttons interfere with header permalinks
* Need to link to a document from SUMMARY.md for it to be rendered

A non-exhaustive list of some key features we do use:
* Mermaid integration
* Full text search
* Pretty default style
* Live reload during editing

**Comment by devender-yadav** [comment] 2018-07-18 06:46
Mkdcos and readthedocs

**Comment by flodolo** [comment] 2018-07-18 07:13
> Mkdcos and readthedocs

readthedocs doesn't work with MarkDown, afaik.

**Comment by mreid-moz** [comment] 2018-07-18 12:46
mdbook and [mkdocs](https://github.com/mkdocs/mkdocs/) both look promising to me.

**Comment by badboy** [comment] 2018-07-19 15:08
Just as a quick test I migrated this repository over to mdbook (in my own fork, with added mermaid functionality).
It's not exactly the same, but very close: https://badboy.github.io/firefox-data-docs/
(Changes visible in https://github.com/badboy/firefox-data-docs/compare/master...badboy:mdbook)

**Comment by harterrt** [comment] 2018-07-19 16:04
@badboy I prefer the format of your new documentation. It fixes #149 ([example](https://badboy.github.io/firefox-data-docs/concepts/choosing_a_dataset.html#longitudinal)). My only critique would be that I'd like the summary to show on the left by default.

**Comment by badboy** [comment] 2018-07-19 16:06
@harterrt Which summary do you mean?

**Comment by badboy** [comment] 2018-07-19 16:33
Meanwhile, I added automatic ToC support (that is `<!-- toc -->` entries are rendered for a certain chapter, [example](https://badboy.github.io/firefox-data-docs/concepts/choosing_a_dataset.html)).

**Comment by harterrt** [comment] 2018-09-06 21:05
Greg's hitting heavy performance losses in #164. If anyone has time to make this change, I'm willing to accept temporary losses to open us up to long term wins. 

@badboy?

**Comment by badboy** [comment] 2018-09-10 09:10
If we want to switch to `mdbook` we want to use [mdbook-dtmo](https://github.com/badboy/mdbook-dtmo), a small wrapper around additional plugins we would need (currently mdbook has no external way for preprocessor plugins).
I can work on a migration script and provide changes for the deployment, but I'd like to see #178 merged first to avoid re-doing that.

**Comment by gregglind** [comment] 2018-09-12 15:53
Update: I used the new mdbook-dtmo script.  I can confirm that it is *very fast* (i.e., 2.6 sec for me).  

Pluses:
- src/ directory is clear.
- numbered bullets on the left in the default theme.

There are still some nits:
- rustup / rust seems like a heavy dependency
- the mdbook-dtmo isn't very verbose yet.  

Thanks for investigating this.

**Comment by badboy** [comment] 2018-09-12 16:03
> rustup / rust seems like a heavy dependency
If we go with that I can provide binaries.

> the mdbook-dtmo isn't very verbose yet.
I am happy to extend it with whatever info we need.

**Comment by badboy** [comment] 2018-09-13 09:30
* [Rendered preview](https://badboy.github.io/firefox-data-docs/)
* [Code](https://github.com/badboy/firefox-data-docs/tree/mdbook-2)
* [Conversion script I used](https://gist.github.com/badboy/382ca15a266ca48839eb2d63ebe05c16)

I also updated mdbook-dtmo to the latest mdbook version to fix some outstanding issues. Right now it doesn't come with `mdbook`'s serve functionality, but I can add that.

@harterrt Should I submit the changes as a PR to get this switched over?

**Comment by harterrt** [comment] 2018-09-13 20:54
@badboy please do.

I'd like for mdbook-dtmo to be merged upstream to mdbook eventually. However, I don't think it makes sense to wait for that upstream merge to happen especially given that gitbook is no longer maintained.

Do you have an ETA for the `serve` command?

**Comment by badboy** [comment] 2018-09-14 09:18
I can copy over the mdbook upstream commands easily, so I can have that ready by next week.
I can also work with upstream to see what we can do about integrating the additional preprocessors (or have an easier plugin system), but I agree that we shouldn’t and can’t wait for that.

**Comment by harterrt** [comment] 2018-09-14 14:32
Sweet. Let's go ahead with that PR. Would you please file a bug to track moving these changes upstream?

Thanks for this, @badboy. Really exciting work!

**Closed** 2018-10-15 10:14 UTC

**Comment by dragosbulugean** [comment] 2020-01-22 18:19
If you're looking for a docs solution (it's also hosted like Gitbook, but we are trying to open source our product) please take a look at [Archbee](https://archbee.io).
