### ISSUE TITLE
Document BigQuery UDFs

### ISSUE THREAD

**Issue by tdsmith** [mozilla/firefox-data-docs#312] opened 2019-08-19 23:10 UTC
These live in https://github.com/mozilla/bigquery-etl/tree/master/udf and https://github.com/mozilla/bigquery-etl/tree/master/udf_js.

Should the documentation be authored in that tree or this one? Should it be published with DTMO or should we just link out to it?

**Comment by tdsmith** [comment] 2019-08-19 23:11
cf https://github.com/mozilla/bigquery-etl/issues/228

**Comment by jklukas** [comment] 2019-08-20 12:27
This looks like largely a duplicate of #228, so closing. But I will add a note on DTMO linking to #228 as a future improvement.

**Closed** 2019-08-20 12:50 UTC
Labels: duplicate
